### ISSUE TITLE
Фогстрим ревью

### ISSUE THREAD

**Issue by nikvst** [NickiHell/fogstream_test#1]
1. Нет файла с зависимостями. Нужен файл requirements, где будут указаны используемые пакеты 
(pip freeze)

2. settings.py
  - Остались стандартные комментарии, их быть не должно;
  - DEBUG = True - если это релиз, то лучше все таки флаг в False по умолчанию поставить;
  - SECRET_KEY находится в публином репозитории, так делать нельзя;
  - локаль и таймзона тоже не исправлена;
  - используется sqlite, в фогстриме мы используем Postgresql, но если условия задачи позволяют, 
    то пусть будет.

  Параметры проекта, которые меняются от стенда к стенду, нужно выносить.
  Какими способами можно задавать подобные параметры?

3. models.py
  - нужна валидация поля email

4. views.py
  - :17 - Здесь все верно? request.user будет AnonymousUser, значит на него и нужно проверять.
  - :18 - если юзер не указан, то это не 404 ошибка, это скорее ошибка авторизации
  - :19 - если после условия сработал return, то нужен ли нам else? можно его убрать 
          и сдвинуть весь последующий код на 4 пробела влево, повысив его читаемость.
  - :20 - слишком большой блок в конструкции try...catch
    :37 - мы ловим абсолютно все ошибки, а значит мы не знаем, какие они могут быть и как их 
          обрабатывать. Так делать не нужно, стоит указывать конкретные классы ошибок.
    :38 - лишние комментарии в релизном коде

  Какой есть общепринятый подход к оформлению и сортировке импортов?
  Какие искоючения мы ожидаем получить в конструкции try...catch в строках 20...36

5. tests.py - пустой шаблонный файл. Если нет тестов, то нужно вообще его удалить.

  В условиях задания указано, что должны быть тесты!

6. Первый релиз проекта, а в нем уже 4 миграции. 

Какие имеются механизмы для уменьшения количества миграций? Когда их можно применять?

7. ??? - очень плохой комментарий для коммита. 

Как в гите можно переименовать коммит? Что будет с хешем переименнованого коммита? 

8. send_mail.html
  - неправильно расставлены отступы
  - :9, :10 - ссылки в django указываются через отдельный тег, см. :8, :13, :14
  - Если пользователь не авторизован, то ему все равно доступна форма отправки, верно? 
    Так быть недолжно.

9. Формы в шаблонах вообще работают? Ни у одной не указан action. Куда передается запрос после нажатия кнопки submit? Если это работает, то почему?

10. не вижу кода, который выполняет отправку email.

11. Нет валидации.

Нужно исправить все замечания. После этого выложить проект на https://www.pythonanywhere.com/.
Простая инструкция по депою - https://tutorial.djangogirls.org/ru/deploy/.
Ответы на вопросы жду в ответном сообщении.

**Comment by NickiHell** [comment]
1) Done
2)SECRET_KEY: задание тестовое, думаю ничего страшного если он здесь побудет.
settings.py: Думаю можно динамически менять как то-так: http://djangopackages.com/grids/g/live-setting/, но разве здесь это необходимо?
3)pep8, неиспользуемые импорты должны удаляться.
4)Немножко поправил.
5)В тестах пока не разобрался нужно больше времени.
6)squashmigrations app миграции
Если миграции сильно разняться, то в итоге может получится не оптимизированная или неработающая миграция, поэтому применять squash нужно только при крайней необходимости, в любом случае джанго прекрасно и быстро может обрабатывать огромное количество миграций.
7)
*)git commit --amend -m 'New commit'
*)git push --force origin 'branch'
*)Хеш изменится. Переименовывать коммиты не рекомендуется, но в текущей ситуации не страшно.
8)Разве? Там ведь POST и возвращает NotAllowed
9)Работает: "<form method="post">"
10)Done
11)К сожалению ajax, jquery пока прикручивать к джанге не умею, если речь о этой валидации.

@nikvst 

Deploy: http://nickihell.pythonanywhere.com/
